name: Transform Design Token
on: 
  push:
    paths:
      - 'data/tokens.json'
jobs:
  transform-design-token:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: 16
      - name: Install Style Dictionary
        run: npm install -g style-dictionary
      - name: Build Style Dictionary
        run: style-dictionary build
